title: Xheldon
description: 会点前端，在学 Node、Electron、ProseMirror
author: Xheldon
highlighter: rouge
github: https://github.com/Xheldon
about: 大前端、工具控、编辑器研究、科幻，十万个为什么。
disqus_shortname: Xheldon
google_analytics: UA-79359216-1
avatar_url: /static/img/logo_min.png
permalink: /:title.html
enableTags: true
tagarray: []
collections:
  project:
    output: true
    permalink: /project/:path

social:
    - icon: fa-weibo
      link: "https://weibo.com/xheldon"
    # - icon: fa-github
    #   link: "https://github.com/Xheldon"
    - icon: fa-twitter
      link: "https://twitter.com/_Xheldon"
# share:
#   twitter_username: agusmakmun6
#   fb_appid: 1749788565247320

urls:
    - text: 关于
      url: /about/
    - text: 书单
      url: /book-list/  
    - text: 作品
      url: /projects/
    - text: 赞赏
      url: /donate/
    - text: 订阅
      url: /feed.xml

url: "https://xheldon.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
future: true
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
